WARNING 2015-09-25 16:05:02,992 views 32174 140496321550144 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 50, in list\n    logger.info(repr(serializer.data))\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 547, in data\n    ret = super(ListSerializer, self).data\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 174, in data\n    self._data = self.to_representation(self.instance)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 500, in to_representation\n    self.child.to_representation(item) for item in iterable\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__\n    self._fetch_all()\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all\n    self._result_cache = list(self.iterator())\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator\n    results = compiler.execute_sql()\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql\n    cursor.execute(sql, params)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute\n    return self.cursor.execute(sql, params)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute\n    return self.cursor.execute(sql, params)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute\n    return self.cursor.execute(query, args)\n', '  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute\n    self.errorhandler(self, exc, value)\n', '  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\n', 'ProgrammingError: (1146, "Table \'test_scalr_cifs.api_resourcelease\' doesn\'t exist")\n']
INFO 2015-09-25 16:31:17,726 views 476 140474884892480 []
INFO 2015-09-25 16:31:47,105 views 560 139715196491584 []
INFO 2015-09-25 17:33:43,764 views 786 139831698413376 []
INFO 2015-09-25 17:34:18,482 views 876 140186103056192 []
INFO 2015-09-25 17:34:32,558 views 934 140471349241664 []
INFO 2015-09-25 17:40:38,175 views 1186 140081016547136 []
INFO 2015-09-25 17:41:08,613 views 1274 139879285954368 []
WARNING 2015-09-25 17:41:35,106 views 1369 139832903169856 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 110, in create\n    resource = Resource.objects.get(guid=guid)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get\n    self.model._meta.object_name\n', 'DoesNotExist: Resource matching query does not exist.\n']
INFO 2015-09-25 17:41:35,246 views 1369 139832903169856 []
WARNING 2015-09-25 17:49:02,901 views 1753 139715870332736 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 112, in create\n    except User.DoesNotExist:\n', "NameError: global name 'User' is not defined\n"]
INFO 2015-09-25 17:49:03,037 views 1753 139715870332736 []
WARNING 2015-09-25 18:27:28,233 views 1964 140004622313280 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 112, in create\n    except User.DoesNotExist:\n', "NameError: global name 'User' is not defined\n"]
INFO 2015-09-25 18:27:28,379 views 1964 140004622313280 []
INFO 2015-09-25 18:29:56,110 views 2073 140021688883008 []
INFO 2015-09-25 19:00:09,902 views 2898 140381861689152 []
INFO 2015-09-25 19:07:00,210 views 3038 140195835848512 []
INFO 2015-09-25 19:10:55,583 views 3169 140131796825920 []
INFO 2015-09-25 19:23:33,153 views 3419 140522404665152 []
WARNING 2015-09-25 19:38:28,964 views 3538 140439387146048 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 122, in create\n    subscriber = Subscriber.objects.get(email=email)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get\n    self.model._meta.object_name\n', 'DoesNotExist: Subscriber matching query does not exist.\n']
INFO 2015-09-25 19:38:29,110 views 3538 140439387146048 []
WARNING 2015-09-25 19:40:19,440 views 3661 140644836407104 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 131, in create\n    lease.resource = resource\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 635, in __set__\n    self.field.rel.to._meta.object_name,\n', 'ValueError: Cannot assign "[]": "ResourceLease.resource" must be a "Resource" instance.\n']
INFO 2015-09-25 19:40:19,594 views 3661 140644836407104 []
WARNING 2015-09-25 19:49:39,031 views 3825 140536386524992 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 131, in create\n    print(\'lease.resource=\'+repr(lease.resource))\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 616, in __get__\n    "%s has no %s." % (self.field.model.__name__, self.field.name)\n', 'RelatedObjectDoesNotExist: ResourceLease has no resource.\n']
INFO 2015-09-25 19:49:39,188 views 3825 140536386524992 []
WARNING 2015-09-25 19:50:09,515 views 3936 140207831840576 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 132, in create\n    lease.resource = resource\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 635, in __set__\n    self.field.rel.to._meta.object_name,\n', 'ValueError: Cannot assign "[]": "ResourceLease.resource" must be a "Resource" instance.\n']
INFO 2015-09-25 19:50:09,683 views 3936 140207831840576 []
WARNING 2015-09-25 19:59:24,032 views 4068 140623750350656 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 114, in create\n    print(\'all_resources=\'+repr(resource.objects.all()))\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 255, in __get__\n    raise AttributeError("Manager isn\'t accessible via %s instances" % type.__name__)\n', "AttributeError: Manager isn't accessible via Resource instances\n"]
INFO 2015-09-25 19:59:24,168 views 4068 140623750350656 []
WARNING 2015-09-25 19:59:57,728 views 4178 140020066461504 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 114, in create\n    print(\'all_resources=\'+repr(Resource.objects.all()))\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 138, in __repr__\n    data = list(self[:REPR_OUTPUT_SIZE + 1])\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__\n    self._fetch_all()\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all\n    self._result_cache = list(self.iterator())\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 254, in iterator\n    for row in compiler.results_iter(results):\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 800, in results_iter\n    row = self.apply_converters(row, converters)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 784, in apply_converters\n    value = converter(value, expression, self.connection, self.query.context)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/operations.py", line 200, in convert_uuidfield_value\n    value = uuid.UUID(value)\n', '  File "/usr/lib/python2.7/uuid.py", line 135, in __init__\n    int = long(hex, 16)\n', "ValueError: invalid literal for long() with base 16: '<function uuid4 at 0x7f58f3a10f5'\n"]
INFO 2015-09-25 19:59:57,864 views 4178 140020066461504 []
WARNING 2015-09-25 20:20:03,931 views 4338 140211640059712 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 133, in create\n    lease.resource = resource\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 635, in __set__\n    self.field.rel.to._meta.object_name,\n', 'ValueError: Cannot assign "[]": "ResourceLease.resource" must be a "Resource" instance.\n']
INFO 2015-09-25 20:20:04,106 views 4338 140211640059712 []
WARNING 2015-09-25 20:21:49,626 views 4447 139726637561664 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 124, in create\n    subscriber = Subscriber.objects.get(email=email)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get\n    self.model._meta.object_name\n', 'DoesNotExist: Subscriber matching query does not exist.\n']
INFO 2015-09-25 20:21:49,771 views 4447 139726637561664 []
WARNING 2015-09-25 20:34:08,764 views 4537 140729665337152 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 128, in create\n    if subscriber == None:\n', "UnboundLocalError: local variable 'subscriber' referenced before assignment\n"]
INFO 2015-09-25 20:34:08,908 views 4537 140729665337152 []
WARNING 2015-09-25 20:34:41,248 views 4623 140292523636544 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 142, in create\n    lease.expires = datetime.date.today() + timedelta(days=term)\n', "NameError: global name 'datetime' is not defined\n"]
INFO 2015-09-25 20:34:41,389 views 4623 140292523636544 []
WARNING 2015-09-25 20:37:23,069 views 4761 140523964872512 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 143, in create\n    lease.expires = datetime.now() + timedelta(days=term)\n', "AttributeError: 'module' object has no attribute 'now'\n"]
INFO 2015-09-25 20:37:23,206 views 4761 140523964872512 []
WARNING 2015-09-25 20:37:55,746 views 4846 140523436111680 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 143, in create\n    lease.expires = datetime.datetime.now() + timedelta(days=term)\n', 'TypeError: unsupported type for timedelta days component: unicode\n']
INFO 2015-09-25 20:37:55,890 views 4846 140523436111680 []
WARNING 2015-09-25 20:38:56,995 views 4933 140280902317888 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 146, in create\n    print(\'lease__id\'+str(lease__id))\n', "NameError: global name 'lease__id' is not defined\n"]
INFO 2015-09-25 20:38:57,149 views 4933 140280902317888 []
WARNING 2015-09-25 20:39:34,576 views 5055 139952325367616 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 157, in create\n    queryset = ResourceSubscriber.objects.filter(resource=resource)\n', "NameError: global name 'ResourceSubscriber' is not defined\n"]
INFO 2015-09-25 20:39:34,743 views 5055 139952325367616 []
INFO 2015-09-25 20:50:09,854 views 5321 139785780987712 []
INFO 2015-09-25 20:59:42,439 views 5485 140276688840512 []
INFO 2015-09-25 21:36:24,579 views 5832 139952127047488 []
INFO 2015-09-25 21:37:54,960 views 6029 139979986380608 []
INFO 2015-09-25 21:40:00,027 views 6254 140513554573120 []
INFO 2015-09-25 21:40:00,147 views 6254 140513554573120 []
INFO 2015-09-25 21:40:00,428 views 6254 140513554573120 []
INFO 2015-09-25 21:40:00,569 views 6254 140513554573120 []
INFO 2015-09-25 21:41:07,519 views 6468 140579387385664 []
INFO 2015-09-25 21:41:07,658 views 6468 140579387385664 []
INFO 2015-09-25 21:41:07,922 views 6468 140579387385664 []
INFO 2015-09-25 21:41:08,064 views 6468 140579387385664 []
INFO 2015-09-25 21:42:57,958 views 6630 140592043464512 []
INFO 2015-09-25 21:42:58,131 views 6630 140592043464512 []
INFO 2015-09-25 21:42:58,419 views 6630 140592043464512 []
INFO 2015-09-25 21:42:58,601 views 6630 140592043464512 []
INFO 2015-09-25 21:44:21,005 views 6818 140245974247232 []
INFO 2015-09-25 21:44:21,147 views 6818 140245974247232 []
INFO 2015-09-25 21:44:21,392 views 6818 140245974247232 []
INFO 2015-09-25 21:44:21,531 views 6818 140245974247232 []
INFO 2015-09-25 21:50:40,034 views 7035 140556637968192 []
INFO 2015-09-25 21:50:40,198 views 7035 140556637968192 []
INFO 2015-09-25 21:50:40,446 views 7035 140556637968192 []
INFO 2015-09-25 21:50:40,583 views 7035 140556637968192 []
INFO 2015-09-25 21:52:05,780 views 7222 139758917564224 []
INFO 2015-09-25 21:52:05,801 views 7222 139758917564224 [OrderedDict([('id', 2), ('expires', '2015-09-26T21:52:05Z'), ('term', 1), ('reminders', 0)])]
Internal Server Error: /lease/v1/leases/1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 79, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 406, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 371, in handle_exception
    response = self.settings.EXCEPTION_HANDLER(exc)
TypeError: custom_exception_handler() takes exactly 2 arguments (1 given)
INFO 2015-09-25 21:52:06,074 views 7222 139758917564224 []
INFO 2015-09-25 21:52:06,322 views 7222 139758917564224 []
INFO 2015-09-25 21:52:06,343 views 7222 139758917564224 [OrderedDict([('id', 3), ('expires', '2015-09-26T21:52:06Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 21:52:06,471 views 7222 139758917564224 []
INFO 2015-09-25 21:54:28,082 views 7410 139936986711872 []
INFO 2015-09-25 21:54:28,104 views 7410 139936986711872 [OrderedDict([('id', 2), ('expires', '2015-09-26T21:54:28Z'), ('term', 1), ('reminders', 0)])]
Internal Server Error: /lease/v1/leases/1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 79, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 406, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 371, in handle_exception
    response = self.settings.EXCEPTION_HANDLER(exc)
TypeError: custom_exception_handler() takes exactly 2 arguments (1 given)
INFO 2015-09-25 21:54:28,233 views 7410 139936986711872 []
INFO 2015-09-25 21:54:28,461 views 7410 139936986711872 []
INFO 2015-09-25 21:54:28,481 views 7410 139936986711872 [OrderedDict([('id', 3), ('expires', '2015-09-26T21:54:28Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 21:54:28,598 views 7410 139936986711872 []
INFO 2015-09-25 21:59:10,193 views 7882 140092235200320 []
INFO 2015-09-25 21:59:10,215 views 7882 140092235200320 [OrderedDict([('id', 2), ('expires', '2015-09-26T21:59:10Z'), ('term', 1), ('reminders', 0)])]
Internal Server Error: /lease/v1/leases/1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 79, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 406, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 371, in handle_exception
    response = self.settings.EXCEPTION_HANDLER(exc)
TypeError: custom_exception_handler() takes exactly 2 arguments (1 given)
INFO 2015-09-25 21:59:10,352 views 7882 140092235200320 []
INFO 2015-09-25 21:59:10,600 views 7882 140092235200320 []
INFO 2015-09-25 21:59:10,620 views 7882 140092235200320 [OrderedDict([('id', 3), ('expires', '2015-09-26T21:59:10Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 21:59:10,742 views 7882 140092235200320 []
INFO 2015-09-25 22:05:26,077 views 8099 140437382096704 []
INFO 2015-09-25 22:05:26,099 views 8099 140437382096704 [OrderedDict([('id', 2), ('expires', '2015-09-26T22:05:26Z'), ('term', 1), ('reminders', 0)])]
Internal Server Error: /lease/v1/leases/1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 79, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 406, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 371, in handle_exception
    response = self.settings.EXCEPTION_HANDLER(exc)
TypeError: custom_exception_handler() takes exactly 2 arguments (1 given)
INFO 2015-09-25 22:05:26,241 views 8099 140437382096704 []
INFO 2015-09-25 22:05:26,485 views 8099 140437382096704 []
INFO 2015-09-25 22:05:26,505 views 8099 140437382096704 [OrderedDict([('id', 3), ('expires', '2015-09-26T22:05:26Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 22:05:26,624 views 8099 140437382096704 []
INFO 2015-09-25 22:06:37,340 views 8260 140197824411456 []
INFO 2015-09-25 22:06:37,360 views 8260 140197824411456 [OrderedDict([('id', 2), ('expires', '2015-09-26T22:06:37Z'), ('term', 1), ('reminders', 0)])]
Internal Server Error: /lease/v1/leases/1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 79, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 406, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 371, in handle_exception
    response = self.settings.EXCEPTION_HANDLER(exc)
TypeError: custom_exception_handler() takes exactly 2 arguments (1 given)
INFO 2015-09-25 22:06:37,488 views 8260 140197824411456 []
INFO 2015-09-25 22:06:37,760 views 8260 140197824411456 []
INFO 2015-09-25 22:06:37,779 views 8260 140197824411456 [OrderedDict([('id', 3), ('expires', '2015-09-26T22:06:37Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 22:06:37,922 views 8260 140197824411456 []
INFO 2015-09-25 22:07:44,004 views 8441 140333248714560 []
INFO 2015-09-25 22:07:44,023 views 8441 140333248714560 [OrderedDict([('id', 2), ('expires', '2015-09-26T22:07:44Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 22:07:44,156 views 8441 140333248714560 []
INFO 2015-09-25 22:07:44,408 views 8441 140333248714560 []
INFO 2015-09-25 22:07:44,427 views 8441 140333248714560 [OrderedDict([('id', 3), ('expires', '2015-09-26T22:07:44Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 22:07:44,558 views 8441 140333248714560 []
INFO 2015-09-25 22:09:28,152 views 8642 140175324829504 []
INFO 2015-09-25 22:09:28,173 views 8642 140175324829504 [OrderedDict([('id', 2), ('expires', '2015-09-26T22:09:28Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 22:09:28,318 views 8642 140175324829504 []
INFO 2015-09-25 22:09:28,608 views 8642 140175324829504 []
INFO 2015-09-25 22:09:28,628 views 8642 140175324829504 [OrderedDict([('id', 3), ('expires', '2015-09-26T22:09:28Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 22:09:28,756 views 8642 140175324829504 []
INFO 2015-09-25 22:09:28,776 views 8642 140175324829504 [OrderedDict([('id', 4), ('expires', '2015-09-26T22:09:28Z'), ('term', 1), ('reminders', 0)])]
INFO 2015-09-25 22:16:30,704 views 9220 139664394458944 []
WARNING 2015-09-25 22:16:30,741 views 9220 139664394458944 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 51, in list\n    logger.info(repr(serializer.data))\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 547, in data\n    ret = super(ListSerializer, self).data\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 174, in data\n    self._data = self.to_representation(self.instance)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 500, in to_representation\n    self.child.to_representation(item) for item in iterable\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 385, in to_representation\n    attribute = field.get_attribute(instance)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 278, in get_attribute\n    return get_attribute(instance, self.source_attrs)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 70, in get_attribute\n    raise exc\n', "AttributeError: 'ResourceLease' object has no attribute 'subscriber'\n"]
INFO 2015-09-25 22:16:30,882 views 9220 139664394458944 []
INFO 2015-09-25 22:16:31,184 views 9220 139664394458944 []
WARNING 2015-09-25 22:16:31,208 views 9220 139664394458944 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 51, in list\n    logger.info(repr(serializer.data))\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 547, in data\n    ret = super(ListSerializer, self).data\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 174, in data\n    self._data = self.to_representation(self.instance)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 500, in to_representation\n    self.child.to_representation(item) for item in iterable\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 385, in to_representation\n    attribute = field.get_attribute(instance)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 278, in get_attribute\n    return get_attribute(instance, self.source_attrs)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 70, in get_attribute\n    raise exc\n', "AttributeError: 'ResourceLease' object has no attribute 'subscriber'\n"]
INFO 2015-09-25 22:16:31,339 views 9220 139664394458944 []
WARNING 2015-09-25 22:16:31,362 views 9220 139664394458944 ['Traceback (most recent call last):\n', '  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 51, in list\n    logger.info(repr(serializer.data))\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 547, in data\n    ret = super(ListSerializer, self).data\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 174, in data\n    self._data = self.to_representation(self.instance)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 500, in to_representation\n    self.child.to_representation(item) for item in iterable\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 385, in to_representation\n    attribute = field.get_attribute(instance)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 278, in get_attribute\n    return get_attribute(instance, self.source_attrs)\n', '  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 70, in get_attribute\n    raise exc\n', "AttributeError: 'ResourceLease' object has no attribute 'subscriber'\n"]
INFO 2015-09-25 22:22:35,715 views 9835 139690029971264 []
INFO 2015-09-25 22:22:35,738 views 9835 139690029971264 [OrderedDict([('id', 2), ('expires', '2015-09-26T22:22:35Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 2), ('guid', u'7ce42cd4-e100-4877-9da3-ab298b04cea8')]))])]
INFO 2015-09-25 22:22:35,877 views 9835 139690029971264 []
INFO 2015-09-25 22:22:36,134 views 9835 139690029971264 []
INFO 2015-09-25 22:22:36,156 views 9835 139690029971264 [OrderedDict([('id', 3), ('expires', '2015-09-26T22:22:36Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 3), ('guid', u'5196d999-3d4c-499a-b7ff-f0abbccbb0cc')]))])]
Internal Server Error: /lease/v1/unlease
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 191, in unlease
    lease = ResourceLease.objects.filter(resource_id=rid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1309, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1337, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1199, in build_filter
    lookups, value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 1756, in get_lookup_constraint
    lookup_class(target.get_col(alias, source), val), AND)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 101, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 139, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 727, in get_prep_lookup
    return self.get_prep_value(value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 985, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '5196d999-3d4c-499a-b7ff-f0abbccbb0cc'
INFO 2015-09-25 22:22:36,328 views 9835 139690029971264 []
INFO 2015-09-25 22:22:36,350 views 9835 139690029971264 [OrderedDict([('id', 4), ('expires', '2015-09-26T22:22:36Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 4), ('guid', u'0630b5d0-a682-471d-97ef-c3a9d55ef33c')]))])]
Internal Server Error: /lease/v1/unsubscribe
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 191, in unlease
    lease = ResourceLease.objects.filter(resource_id=rid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1309, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1337, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1199, in build_filter
    lookups, value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 1756, in get_lookup_constraint
    lookup_class(target.get_col(alias, source), val), AND)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 101, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 139, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 727, in get_prep_lookup
    return self.get_prep_value(value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 985, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '0630b5d0-a682-471d-97ef-c3a9d55ef33c'
INFO 2015-09-25 22:31:31,472 views 10025 140265179432768 []
INFO 2015-09-25 22:31:31,497 views 10025 140265179432768 [OrderedDict([('id', 2), ('expires', '2015-09-26T22:31:31Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 2), ('guid', u'2b0b9374-4cd7-47e5-992b-ef70d2b74255')]))])]
INFO 2015-09-25 22:31:31,625 views 10025 140265179432768 []
INFO 2015-09-25 22:31:31,869 views 10025 140265179432768 []
INFO 2015-09-25 22:31:31,892 views 10025 140265179432768 [OrderedDict([('id', 3), ('expires', '2015-09-26T22:31:31Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 3), ('guid', u'f64edd1e-98bb-4142-b481-937e3103b555')]))])]
INFO 2015-09-25 22:31:32,029 views 10025 140265179432768 []
INFO 2015-09-25 22:31:32,052 views 10025 140265179432768 [OrderedDict([('id', 4), ('expires', '2015-09-26T22:31:32Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 4), ('guid', u'39d350e9-962c-4080-802c-f0c0b4e21477')]))])]
INFO 2015-09-25 22:33:40,132 views 10187 139680105543488 []
INFO 2015-09-25 22:33:40,155 views 10187 139680105543488 [OrderedDict([('id', 2), ('expires', '2015-09-26T22:33:40Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 2), ('guid', u'38f29c59-f6c4-434a-aa5e-38ba14ae9003')]))])]
INFO 2015-09-25 22:33:40,278 views 10187 139680105543488 []
INFO 2015-09-25 22:33:40,512 views 10187 139680105543488 []
INFO 2015-09-25 22:33:40,535 views 10187 139680105543488 [OrderedDict([('id', 3), ('expires', '2015-09-26T22:33:40Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 3), ('guid', u'570306df-a5c7-4f50-9d0d-0cdf3b0f5c9f')]))])]
Internal Server Error: /lease/v1/unlease
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 191, in unlease
    lease = ResourceLease.objects.filter(resource_id=rid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1309, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1337, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1199, in build_filter
    lookups, value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 1756, in get_lookup_constraint
    lookup_class(target.get_col(alias, source), val), AND)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 101, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 139, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 727, in get_prep_lookup
    return self.get_prep_value(value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 985, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '570306df-a5c7-4f50-9d0d-0cdf3b0f5c9f'
INFO 2015-09-25 22:33:40,670 views 10187 139680105543488 []
INFO 2015-09-25 22:33:40,692 views 10187 139680105543488 [OrderedDict([('id', 4), ('expires', '2015-09-26T22:33:40Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 4), ('guid', u'a86593ad-d5ee-4d15-91e5-f2892c9ffb64')]))])]
Internal Server Error: /lease/v1/unsubscribe
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/GitHub/new/leaseapi/leaseapi/api/v1/views.py", line 191, in unlease
    lease = ResourceLease.objects.filter(resource_id=rid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1309, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1337, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1199, in build_filter
    lookups, value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 1756, in get_lookup_constraint
    lookup_class(target.get_col(alias, source), val), AND)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 101, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 139, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 727, in get_prep_lookup
    return self.get_prep_value(value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 985, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'a86593ad-d5ee-4d15-91e5-f2892c9ffb64'
INFO 2015-09-25 22:40:57,627 views 10479 140214525409088 []
INFO 2015-09-25 22:40:57,650 views 10479 140214525409088 [OrderedDict([('id', 2), ('expires', '2015-09-26T22:40:57Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 2), ('guid', u'79debdcb-97df-45f9-9900-8b9e2a84d5db')]))])]
INFO 2015-09-25 22:40:57,790 views 10479 140214525409088 []
INFO 2015-09-25 22:40:58,092 views 10479 140214525409088 []
INFO 2015-09-25 22:40:58,116 views 10479 140214525409088 [OrderedDict([('id', 3), ('expires', '2015-09-26T22:40:58Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 3), ('guid', u'416dade4-f1f0-4da2-bd2b-3a8fc9550645')]))])]
INFO 2015-09-25 22:40:58,270 views 10479 140214525409088 []
INFO 2015-09-25 22:40:58,293 views 10479 140214525409088 [OrderedDict([('id', 4), ('expires', '2015-09-26T22:40:58Z'), ('term', 1), ('reminders', 0), ('resource', OrderedDict([('id', 4), ('guid', u'e286b733-c3e3-4a3c-afd6-0d8b392baf17')]))])]
